### PR TITLE
Add more user info to info

### PR DESCRIPTION
**Pull request by gssbzn**
Add time zone, more image sizes to choose and info about admin and owner properties

### CODE REVIEW

**Comment by ColbyAley** [comment]
if there anything stopping this from getting merged @kmrshntr?

**Comment by kmrshntr** [comment]
I thought this is too tightly coupled with Slack API, isn't it?
If the API changes, we need to change here.

**Comment by captn3m0** [comment]
I think its fine. Its a slack integration. Makes sense to be dependent on it.

**Comment by kmrshntr** [comment]
OK. I could understand. 
Let's follow up the API changes from now on. :wink:

**Comment by gssbzn** [comment]
The integration with the API for information was added here ff5946e9e8a95b8cfe300eee488c0a3e9989a226, I just added some more info that we are using (and some other people might use) since we don't want to make a second call to the same endpoint.
Thx for the marge

**Comment by kmrshntr** [comment]
Sorry for late.

**Pull request merged**
