### PR TITLE
Add bot user info per Slack API updates

### PR DESCRIPTION
**Pull request by hpoydar**
Adds access to `bot_access_token` and `bot_user_id` params if the `bot` scope is provided https://api.slack.com/bot-users

### CODE REVIEW

**Comment by jwright** [comment]
:+1:

**Comment by kandadaboggu** [comment]
:+1:

**Comment by danielmackey** [comment]
:+1:

**Comment by kmrshntr** [comment]
Now I released as v2.3.0.
@hpoydar  Thank you :smile:

**Pull request merged**
